import { describe, expect, it } from "vitest"
import { isAutoGeneratedColumn } from "@/lib/schema-utils"
import type { ColumnInfo } from "@/lib/schema-introspection"

const baseColumn = {
  table: { schema: "public", name: "users" },
  name: "id",
  dataType: "uuid",
  isNullable: false,
} satisfies ColumnInfo

describe("schema-utils", () => {
  it("detects identity/generated columns", () => {
    expect(isAutoGeneratedColumn({ ...baseColumn, isIdentity: true })).toBe(true)
    expect(isAutoGeneratedColumn({ ...baseColumn, isGenerated: true })).toBe(true)
    expect(isAutoGeneratedColumn({ ...baseColumn, generationExpression: "expr" })).toBe(true)
  })

  it("detects default functions like now() and uuid generators", () => {
    expect(isAutoGeneratedColumn({ ...baseColumn, defaultValue: "now()" })).toBe(true)
    expect(isAutoGeneratedColumn({ ...baseColumn, defaultValue: "CURRENT_TIMESTAMP" })).toBe(true)
    expect(isAutoGeneratedColumn({ ...baseColumn, defaultValue: "gen_random_uuid()" })).toBe(true)
    expect(isAutoGeneratedColumn({ ...baseColumn, defaultValue: "uuid_generate_v4()" })).toBe(true)
    expect(isAutoGeneratedColumn({ ...baseColumn, defaultValue: "nextval('users_id_seq'::regclass)" })).toBe(true)
  })

  it("treats plain defaults as non-auto", () => {
    expect(isAutoGeneratedColumn({ ...baseColumn, defaultValue: "'active'::text" })).toBe(false)
  })
})
