"use client"

import { useCallback, useEffect, useMemo, useState, useRef } from "react"
import { SchemasSidebar } from "./schemas-sidebar"
import { SlowQueryPanel } from "./slow-query-panel"
import { QueryHistoryPanel } from "./query-history-panel"
import { SchemaGraphView } from "./schema-graph-view"
import { QueryTabs, type Tab } from "./query-tabs"
import { QueryEditor } from "./query-editor"
import { NamedQueryEditor, type NamedQuery, type NamedQueryParamMeta } from "./named-query-editor"
import { SaveNamedQueryDialog } from "./save-named-query-dialog"
import { DataGrid } from "./data-grid"
import { ConnectionDialog } from "./connection-dialog"
import { SyncSettingsDialog } from "./sync-settings-dialog"
import { NamedQuerySyncConflictsDialog } from "./named-query-sync-conflicts-dialog"
import { ToastAction } from "@/components/ui/toast"
import { Button } from "@/components/ui/button"
import { ResizablePanelGroup, ResizablePanel, ResizableHandle, type ImperativePanelHandle } from "@/components/ui/resizable"
import { Settings, PanelLeftClose, PanelLeft, Sparkles } from "lucide-react"
import { useToast } from "@/hooks/use-toast"
import type { ClientConnectionMeta } from "@/lib/connections"
import type { SchemaGraph } from "@/lib/schema-introspection"
import { hasLimitClause, isReadOnlySql } from "@/lib/sql/safety"
import { ApiError, apiClient, asQueryErrorBody, type NamedQuerySyncResolution } from "@/lib/client/apiClient"
import { useCommand } from "@/components/shortcuts/useCommand"
import { CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator, CommandShortcut } from "@/components/ui/command"
import { listCommands } from "@/lib/shortcuts/commands"
import { useShortcutsContext } from "@/components/shortcuts/ShortcutsProvider"
import { parseBinding } from "@/lib/shortcuts/parse"
import { formatBinding } from "@/lib/shortcuts/format"
import { cn } from "@/lib/utils"
import { MenuHandler } from "./menu-handler"
import { GenerateWriteQueryDialog, type WriteQueryMode } from "./generate-write-query-dialog"
import { SaveGeneratorDialog } from "./save-generator-dialog"
import { guessParamType, isAutoGeneratedColumn } from "@/lib/schema-utils"
import { quoteIdent } from "@/lib/sql/quote-ident"
import { generateWriteSql, type GeneratorConfig, type GeneratorMode, type GeneratorParamState } from "@/lib/write-query-generator"


type PoolMode = "single" | "shared" | "per-scope"
const GENERATOR_TEMPLATE_PREFIX = "-- dbconsole:generator "

function encodeGeneratorTemplate(config: { mode: GeneratorMode; table: { schema: string; name: string }; roles?: Record<string, "set" | "where"> }): string {
  return `${GENERATOR_TEMPLATE_PREFIX}${JSON.stringify({ version: 1, kind: "generator", ...config })}`
}

function decodeGeneratorTemplate(sqlTemplate: string): { mode: GeneratorMode; table: { schema: string; name: string }; roles?: Record<string, "set" | "where"> } | null {
  if (!sqlTemplate.startsWith(GENERATOR_TEMPLATE_PREFIX)) return null
  const raw = sqlTemplate.slice(GENERATOR_TEMPLATE_PREFIX.length)
  try {
    const parsed = JSON.parse(raw)
    if (parsed?.kind !== "generator") return null
    if (parsed?.version !== 1) return null
    if (!parsed?.mode || !parsed?.table?.schema || !parsed?.table?.name) return null
    return { mode: parsed.mode, table: parsed.table, roles: parsed.roles }
  } catch {
    return null
  }
}

const cleanPositionalPlaceholders = (sql: string): string =>
  sql.replace(/(['"])\$(\d+)\1/g, (_m, _quote, num) => `$${num}`)

const deriveParamLabels = (sql: string, maxIndex: number): string[] => {
  const labels: string[] = Array.from({ length: maxIndex }, () => "")
  const regex = /([\w."`.]+)\s*(?:=|<>|!=|<|>|<=|>=|LIKE|ILIKE|IN)\s*\$(\d+)/gi
  let match: RegExpExecArray | null
  while ((match = regex.exec(sql))) {
    const column = match[1]?.replace(/["`]/g, "")
    const idx = Number(match[2]) - 1
    if (idx >= 0 && idx < maxIndex && column) {
      labels[idx] = column
    }
  }
  return labels
}

function getErrorInfo(e: any): { status?: number; body?: any; message: string } {
  if (e instanceof ApiError) return { status: e.status, body: e.body, message: e.message }

  const status = typeof e?.status === "number" ? e.status : undefined
  const body = e?.body
  const message =
    typeof e?.message === "string"
      ? e.message
      : typeof body?.error === "string"
        ? body.error
        : "Unknown error"

  return { status, body, message }
}

const toSqlLiteral = (v: unknown): string => {
  if (v === null || v === undefined) return "NULL"
  if (typeof v === "number" || typeof v === "bigint") return String(v)
  if (typeof v === "boolean") return v ? "TRUE" : "FALSE"
  const s = String(v).replace(/'/g, "''")
  return `'${s}'`
}

const renderSqlWithParams = (sql: string, params: unknown[]): string =>
  sql.replace(/\$(\d+)/g, (_m, idx) => {
    const i = Number(idx) - 1
    return toSqlLiteral(params[i] ?? null)
  })

const escapeRegex = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$")

const buildGeneratorParams = (
  schema: SchemaGraph | null,
  table: { schema: string; name: string },
  mode: GeneratorMode,
  roles?: Record<string, "set" | "where">,
): GeneratorParamState[] => {
  if (!schema) return []
  const cols = schema.columns.filter((c) => c.table.schema === table.schema && c.table.name === table.name)
  const pkSet = new Set(
    schema.primaryKeys
      .filter((pk) => pk.table.schema === table.schema && pk.table.name === table.name)
      .map((pk) => pk.columnName),
  )

  return cols.map((c) => {
    const isPk = pkSet.has(c.name)
    const role = mode === "update" ? (roles?.[c.name] ?? (isPk ? "where" : "set")) : undefined
    return {
      name: c.name,
      dataType: c.dataType,
      inputType: guessParamType(c.dataType),
      isNullable: c.isNullable,
      isAuto: isAutoGeneratedColumn(c),
      isPk,
      role,
      overrideAuto: false,
      isNull: false,
      value: "",
    }
  })
}

const buildGeneratorNamedQuery = (tab: Tab): NamedQuery | null => {
  if (!tab.isGenerator || !tab.generator) return null
  return {
    id: `generator-${tab.id}`,
    name: tab.name,
    description: tab.generator.mode === "insert"
      ? "Empty fields are skipped. Auto-generated columns are skipped unless overridden."
      : "Empty fields are skipped. Mark columns as WHERE to target rows safely.",
    query: "",
    parameters: tab.generator.params.map((p) => ({ name: p.name, type: p.inputType })),
  }
}

const buildGeneratorParamMeta = (tab: Tab): Record<string, NamedQueryParamMeta> => {
  if (!tab.isGenerator || !tab.generator) return {}
  return tab.generator.params.reduce<Record<string, NamedQueryParamMeta>>((acc, p) => {
    acc[p.name] = {
      dataType: p.dataType,
      isNullable: p.isNullable,
      isAuto: p.isAuto,
      isPk: p.isPk,
      role: p.role,
      overrideAuto: p.overrideAuto,
      isNull: p.isNull,
    }
    return acc
  }, {})
}


interface JoinConfig {
  table: string
  leftTable?: string
  leftColumn: string
  rightColumn: string
  joinType: "INNER" | "LEFT" | "RIGHT" | "FULL"
}

interface ConnectionWithStatus extends ClientConnectionMeta {
  status: "connected" | "connecting" | "disconnected"
}

export function DbConsole() {
  const { toast } = useToast()
  const shortcuts = useShortcutsContext()
  const [sidebarOpen, setSidebarOpen] = useState(true)
  const [sidebarTab, setSidebarTab] = useState<"tables" | "queries">("tables")
  const [commandPaletteOpen, setCommandPaletteOpen] = useState(false)
  const [sidebarActionsShowOnHover, setSidebarActionsShowOnHover] = useState(true)

  const topPanelRef = useRef<ImperativePanelHandle | null>(null)
  const verticalGroupRef = useRef<HTMLDivElement | null>(null)

  const [activeTab, setActiveTab] = useState("query-1")
  const [tabs, setTabs] = useState<Tab[]>([
    { id: "query-1", name: "Query 1", query: "", pagination: { limit: 100, offset: 0 } }
  ])
  const [poolMode, setPoolMode] = useState<PoolMode>(() => {
    if (typeof window === "undefined") return "shared"
    const stored = localStorage.getItem("db-console-pool-mode") as PoolMode | null
    return stored ?? "shared"
  })

  // Global state for params expanded - applies to all named query tabs, default collapsed
  const [globalParamsExpanded, setGlobalParamsExpanded] = useState(false)

  // Persistence: Restore tabs on mount
  useEffect(() => {
    try {
      const savedTabs = localStorage.getItem("db-console-tabs-v1")
      const savedActive = localStorage.getItem("db-console-active-tab-v1")
      if (savedTabs) {
        setTabs(JSON.parse(savedTabs))
      }
      if (savedActive) {
        setActiveTab(savedActive)
      }
    } catch (e) {
      console.error("Failed to restore tabs", e)
    }
  }, [])

  // Persistence: Save tabs and pool mode on change
  useEffect(() => {
    try {
      localStorage.setItem("db-console-tabs-v1", JSON.stringify(tabs))
      localStorage.setItem("db-console-active-tab-v1", activeTab)
      localStorage.setItem("db-console-pool-mode", poolMode)
    } catch (e) {
      console.error("Failed to save tabs", e)
    }
  }, [tabs, activeTab, poolMode])

  const [connections, setConnections] = useState<ConnectionWithStatus[]>([])
  const [activeConnection, setActiveConnection] = useState<string | null>(null)

  // Persistence: Save active connection on change
  useEffect(() => {
    if (activeConnection) {
      try {
        localStorage.setItem("db-console-last-connection-id", activeConnection)
      } catch (e) {
        console.error("Failed to save last connection", e)
      }
    }
  }, [activeConnection])
  const [showConnectionDialog, setShowConnectionDialog] = useState(false)

  const [namedQueries, setNamedQueries] = useState<NamedQuery[]>([])
  const [showSaveNamedDialog, setShowSaveNamedDialog] = useState(false)
  const [editingNamedQuery, setEditingNamedQuery] = useState<NamedQuery | null>(null)
  const [showGenerateDialog, setShowGenerateDialog] = useState(false)
  const [showSaveGeneratorDialog, setShowSaveGeneratorDialog] = useState(false)
  const [savingGeneratorTab, setSavingGeneratorTab] = useState<Tab | null>(null)

  const [showSyncSettingsDialog, setShowSyncSettingsDialog] = useState(false)
  const [syncBusy, setSyncBusy] = useState(false)
  const [syncConflicts, setSyncConflicts] = useState<any[] | null>(null)
  const [showSyncConflictsDialog, setShowSyncConflictsDialog] = useState(false)
  const autoSyncTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const [resultsByTab, setResultsByTab] = useState<{
    [tabId: string]: {
      columns: string[]
      rows: Record<string, unknown>[]
      durationMs: number
      sqlDisplay?: string
      truncated?: boolean
      truncatedAt?: number
      requestedLimit?: number
    } | undefined
  }>({})
  const [schema, setSchema] = useState<SchemaGraph | null>(null)
  const [isRunning, setIsRunning] = useState(false)
  const [error, setError] = useState<string | null>(null)
  /**
   * Per-tab streaming state. When set, the tab is currently consuming a
   * server-side cursor: streamId identifies the open stream and rowsSent
   * tracks how many rows have been delivered so far. The grid renders a
   * "Load more" footer instead of pagination controls.
   */
  const [streamsByTab, setStreamsByTab] = useState<{
    [tabId: string]: { streamId: string; rowsSent: number; hasMore: boolean; loading: boolean } | undefined
  }>({})
  const [showSlowQueries, setShowSlowQueries] = useState(false)
  const [showQueryHistory, setShowQueryHistory] = useState(false)

  const openSqlInNewTab = useCallback(
    (sql: string, name?: string) => {
      const newId = `query-${Date.now()}`
      setTabs((prev) => [
        ...prev,
        {
          id: newId,
          name: name?.trim() || `Query ${prev.length + 1}`,
          query: sql,
          connectionId: activeConnection ?? undefined,
        },
      ])
      setActiveTab(newId)
    },
    [activeConnection],
  )

  // Open or focus the schema-graph tab. Creates a single dedicated tab so the
  // user doesn't end up with five identical schema-graph tabs in their
  // workspace; if one already exists for the active connection, just focus it.
  const openSchemaGraphTab = useCallback(() => {
    if (!activeConnection) return
    const existing = tabs.find((t) => t.isSchemaGraph && t.connectionId === activeConnection)
    if (existing) {
      setActiveTab(existing.id)
      return
    }
    const newId = `schema-graph-${Date.now()}`
    setTabs((prev) => [
      ...prev,
      {
        id: newId,
        name: "Schema graph",
        query: "",
        isSchemaGraph: true,
        connectionId: activeConnection,
      },
    ])
    setActiveTab(newId)
  }, [activeConnection, tabs])

  // Listen for Tools menu actions from the macOS application menu.
  useEffect(() => {
    if (typeof window === "undefined" || !window.dbconsole?.isDesktop) return
    const dc = window.dbconsole
    const offHistory = dc.events.onMenuQueryHistory(() => setShowQueryHistory(true))
    const offSlow = dc.events.onMenuSlowQueries(() => setShowSlowQueries(true))
    const offGraph = dc.events.onMenuSchemaGraph(() => openSchemaGraphTab())
    return () => {
      offHistory()
      offSlow()
      offGraph()
    }
  }, [openSchemaGraphTab])

  useEffect(() => {
    const events = typeof window !== "undefined" ? window.dbconsole?.events : undefined
    if (!events?.onSqlFileOpen) return
    const unsubscribe = events.onSqlFileOpen((payload) => {
      if (!payload || !payload.sql) return
      openSqlInNewTab(payload.sql, payload.name)
    })
    return unsubscribe
  }, [openSqlInNewTab])

  const loadSchema = useCallback(async (connectionId: string) => {
    try {
      const graph = await apiClient.schema.load(connectionId)
      setSchema(graph)
    } catch (e: any) {
      console.error("Failed to load schema", e)
      toast({
        variant: "destructive",
        title: "Failed to load schema",
        description: e?.message || "Could not load database schema.",
      })
    }
  }, [toast])

  const reloadNamedQueries = useCallback(async () => {
    const raw = await apiClient.namedQueries.list()
    if (Array.isArray(raw)) {
      const mapped: NamedQuery[] = raw.map((q: any) => ({
        id: q.id,
        name: q.name,
        description: q.description,
        query: q.sqlTemplate,
        parameters: q.params,
      }))
      setNamedQueries(mapped)
    }
  }, [])

  const handleSyncNamedQueries = useCallback(async () => {
    if (syncBusy) return
    setSyncBusy(true)
    try {
      await apiClient.syncer.namedQueries.sync()
      await reloadNamedQueries()
      toast({ title: "Synced saved queries" })
    } catch (e: any) {
      const info = getErrorInfo(e)

      if (info.status === 409 || info.message === "Conflicts") {
        const conflicts = info.body?.conflicts
        if (Array.isArray(conflicts)) {
          setSyncConflicts(conflicts)
          setShowSyncConflictsDialog(true)
          toast({
            title: "Sync needs attention",
            description: "Resolve conflicts to continue.",
            action: (
              <ToastAction altText="Resolve" onClick={() => setShowSyncConflictsDialog(true)}>
                Resolve
              </ToastAction>
            ),
          })
        } else {
          toast({ variant: "destructive", title: "Sync conflict", description: info.message })
        }
      } else if (info.status === 400) {
        // Missing local settings (remote URL / phrase)
        setShowSyncSettingsDialog(true)
        toast({ variant: "destructive", title: "Sync not configured", description: info.message })
      } else {
        toast({ variant: "destructive", title: "Sync failed", description: info.message })
      }
    } finally {
      setSyncBusy(false)
    }
  }, [reloadNamedQueries, syncBusy, toast])

  // Desktop-only: menu items + persisted UI preference (sidebar action hover behavior)
  useEffect(() => {
    const dc = typeof window !== "undefined" ? window.dbconsole : undefined
    if (!dc?.isDesktop) return

    const api = dc?.api
    const events = dc?.events

    let cancelled = false

      ; (async () => {
        try {
          const res = await api?.uiPrefs?.get?.("sidebarActionsShowOnHover")
          const value = res?.value
          if (!cancelled && typeof value === "boolean") {
            setSidebarActionsShowOnHover(value)
          }
        } catch {
          // ignore (default true)
        }
      })()

    const unsubHover = events?.onMenuSidebarActionsShowOnHover?.((payload: any) => {
      const enabled = payload?.enabled
      if (typeof enabled === "boolean") setSidebarActionsShowOnHover(enabled)
    })

    const unsubSyncNow = events?.onMenuSyncNow?.(() => {
      void handleSyncNamedQueries()
    })

    const unsubSyncSettings = events?.onMenuSyncSettings?.(() => {
      setShowSyncSettingsDialog(true)
    })

    return () => {
      cancelled = true
      unsubHover?.()
      unsubSyncNow?.()
      unsubSyncSettings?.()
    }
  }, [handleSyncNamedQueries])

  const scheduleAutoSyncNamedQueries = useCallback(() => {
    if (autoSyncTimerRef.current) clearTimeout(autoSyncTimerRef.current)
    autoSyncTimerRef.current = setTimeout(() => {
      void handleSyncNamedQueries()
    }, 300)
  }, [handleSyncNamedQueries])

  const applySyncResolutions = useCallback(async (resolutions: NamedQuerySyncResolution[]) => {
    if (syncBusy) return
    setSyncBusy(true)
    try {
      await apiClient.syncer.namedQueries.sync({ resolutions })
      await reloadNamedQueries()
      setShowSyncConflictsDialog(false)
      setSyncConflicts(null)
      toast({ title: "Synced saved queries" })
    } catch (e: any) {
      const info = getErrorInfo(e)
      if (info.status === 409 || info.message === "Conflicts") {
        const conflicts = info.body?.conflicts
        if (Array.isArray(conflicts)) {
          setSyncConflicts(conflicts)
          setShowSyncConflictsDialog(true)
          return
        }
      }
      toast({ variant: "destructive", title: "Sync failed", description: info.message })
    } finally {
      setSyncBusy(false)
    }
  }, [reloadNamedQueries, syncBusy, toast])

  // Load initial connections & named queries on mount
  useEffect(() => {
    const controller = new AbortController()

    async function loadInitial() {
      try {
        const [conns, raw] = await Promise.all([
          apiClient.connections.list({ signal: controller.signal }),
          apiClient.namedQueries.list({ signal: controller.signal }),
        ])

        if (Array.isArray(conns)) {
          if (conns.length > 0) {
            let initialConnectionId = conns[0].id  // Default: first connection

            // Try to restore last used connection
            try {
              const savedConnectionId = localStorage.getItem("db-console-last-connection-id")
              if (savedConnectionId) {
                const exists = conns.some(c => c.id === savedConnectionId)
                if (exists) {
                  initialConnectionId = savedConnectionId
                }
              }
            } catch (e) {
              console.error("Failed to restore last connection", e)
            }

            // Set connection statuses based on which one is active
            const withStatus: ConnectionWithStatus[] = conns.map(c => ({
              ...c,
              status: c.id === initialConnectionId ? "connected" : "disconnected",
            }))
            setConnections(withStatus)
            setActiveConnection(initialConnectionId)
            void loadSchema(initialConnectionId)
          } else {
            setConnections([])
          }
        }

        if (Array.isArray(raw)) {
          const mapped: NamedQuery[] = raw.map((q: any) => ({
            id: q.id,
            name: q.name,
            description: q.description,
            query: q.sqlTemplate,
            parameters: q.params,
          }))
          setNamedQueries(mapped)
        }
      } catch (e: any) {
        console.error("Failed to load initial data", e)
        toast({
          variant: "destructive",
          title: "Failed to load initial data",
          description: e?.message || "Could not load connections and named queries.",
        })
      }
    }

    void loadInitial()

    return () => {
      controller.abort()
    }
  }, [loadSchema, toast])

  const addTab = useCallback(() => {
    openSqlInNewTab("")
  }, [openSqlInNewTab])

  const closeTab = (id: string) => {
    if (tabs.length === 1) return
    const closingTabIndex = tabs.findIndex((t) => t.id === id)
    const closingTab = closingTabIndex >= 0 ? tabs[closingTabIndex] : undefined
    const newTabs = tabs.filter((t) => t.id !== id)
    setTabs(newTabs)
    // Tear down any open stream attached to this tab so we don't leak the
    // pg client checked out for the cursor's transaction.
    if (streamsByTab[id]) void closeStreamForTab(id)
    // If we are using per-tab pools, release the tab-specific pool on close.
    if (poolMode === "per-scope" && closingTab?.connectionId) {
      void apiClient.connections.releasePools({
        connectionId: closingTab.connectionId,
        poolMode,
        scopeKey: id,
      }).catch(() => { })
    }
    if (activeTab === id && newTabs.length > 0) {
      const nextIndex = Math.max(0, closingTabIndex - 1)
      const nextTab = newTabs[nextIndex] ?? newTabs[newTabs.length - 1]
      if (nextTab) setActiveTab(nextTab.id)
    }
  }

  const reorderTabs = useCallback((reorderedTabs: Tab[]) => {
    setTabs(reorderedTabs)
  }, [])

  useCommand("tabs.newQuery", () => addTab())

  useCommand("tabs.close", () => {
    if (!activeTab) return
    closeTab(activeTab)
  })

  useCommand("tabs.next", () => {
    if (!tabs.length) return
    const idx = tabs.findIndex((t) => t.id === activeTab)
    const next = tabs[(idx + 1) % tabs.length]
    if (next) setActiveTab(next.id)
  })

  useCommand("tabs.prev", () => {
    if (!tabs.length) return
    const idx = tabs.findIndex((t) => t.id === activeTab)
    const prev = tabs[(idx - 1 + tabs.length) % tabs.length]
    if (prev) setActiveTab(prev.id)
  })

  useCommand("file.openSql", () => {
    const api = typeof window !== "undefined" ? window.dbconsole?.api?.sqlFile : undefined
    if (!api?.openDialog) return
    void api.openDialog().then((payload: any) => {
      if (payload && typeof payload.sql === "string") {
        openSqlInNewTab(payload.sql, payload.name)
      }
    })
  })

  useCommand("ui.toggleSchemaSidebar", () => setSidebarOpen((prev) => !prev))

  useCommand("ui.openConnections", () => setShowConnectionDialog(true))

  useCommand("ui.focusSidebarSearch", () => {
    const el = typeof document !== "undefined" ? document.getElementById("schema-sidebar-search") : null
    if (el && "focus" in el) (el as any).focus()
  })

  useCommand("ui.showSavedQueriesTab", () => {
    setSidebarOpen(true)
    setSidebarTab("queries")
  })

  useCommand("ui.commandPalette", () => setCommandPaletteOpen(true))

  useCommand("schema.refresh", () => {
    if (activeConnection) void loadSchema(activeConnection)
  })

  useCommand("sync.openSettings", () => setShowSyncSettingsDialog(true))
  useCommand("sync.namedQueriesNow", () => {
    void handleSyncNamedQueries()
  })

  useCommand("ui.focusQueryPanel", () => {
    // Named query / generator tab: prefer focusing first param; if no params, focus Run.
    if ((currentTab?.isNamedQuery && currentNamedQuery) || (currentTab?.isGenerator && currentGeneratorQuery)) {
      const paramCount = currentGeneratorQuery?.parameters.length ?? currentNamedQuery?.parameters.length ?? 0
      if (paramCount > 0) {
        const el = typeof document !== "undefined"
          ? (document.querySelector('[data-named-query-param="1"]') as HTMLInputElement | null)
          : null
        if (el) {
          el.focus()
          // Put caret at end when a value exists (consistent with SQL editor behavior)
          const len = el.value?.length ?? 0
          try {
            el.setSelectionRange(len, len)
          } catch { }
          return true
        }
      }

      const runBtn = typeof document !== "undefined"
        ? (document.querySelector('[data-named-query-run="1"]') as HTMLButtonElement | null)
        : null
      if (runBtn) {
        runBtn.focus()
        return true
      }
      return false
    }

    // Raw query tab: click the SqlEditor container so it focuses and moves caret to end.
    const editorRoot = typeof document !== "undefined" ? (document.getElementById("sql-editor-main") as HTMLElement | null) : null
    if (editorRoot) {
      editorRoot.click()
      return true
    }
    return false
  })

  const updateQuery = (id: string, query: string) => {
    setTabs(tabs.map((t) => {
      if (t.id !== id) return t
      // auto-grow params array to match highest $n placeholder found
      const match = [...query.matchAll(/\$([1-9]\d*)/g)]
      const maxIndex = match.length > 0 ? Math.max(...match.map(m => Number(m[1]) || 0)) : 0
      const existingParams = t.params ?? []
      let params = existingParams
      if (maxIndex > existingParams.length) {
        const extra = Array.from({ length: maxIndex - existingParams.length }, () => ({ type: "string" as const, value: "" }))
        params = [...existingParams, ...extra]
      } else if (maxIndex < existingParams.length) {
        params = existingParams.slice(0, maxIndex)
      }
      return { ...t, query, params }
    }))
  }

  const updateParams = (id: string, params: Tab["params"]) => {
    setTabs(tabs.map((t) => (t.id === id ? { ...t, params } : t)))
  }

  const handleSaveAsNamed = async (namedQuery: Omit<NamedQuery, "id">) => {
    try {
      const saved = await apiClient.namedQueries.save({
        name: namedQuery.name,
        description: namedQuery.description,
        sqlTemplate: namedQuery.query,
        params: namedQuery.parameters,
        defaultConnectionId: activeConnection ?? undefined,
      })

      const newNamedQuery: NamedQuery = {
        id: saved.id,
        name: saved.name,
        description: saved.description,
        query: saved.sqlTemplate,
        parameters: saved.params,
      }

      setNamedQueries((prev) => [...prev, newNamedQuery])

      setTabs((prevTabs) =>
        prevTabs.map((t) =>
          t.id === activeTab
            ? { ...t, name: namedQuery.name, isNamedQuery: true, namedQueryId: newNamedQuery.id }
            : t,
        ),
      )

      scheduleAutoSyncNamedQueries()
    } catch (e) {
      console.error("Failed to save named query", e)
    }
  }

  const handleUpdateNamedQuery = async (updatedQuery: NamedQuery) => {
    try {
      const saved = await apiClient.namedQueries.update(updatedQuery.id, {
        name: updatedQuery.name,
        description: updatedQuery.description,
        sqlTemplate: updatedQuery.query,
        params: updatedQuery.parameters,
        defaultConnectionId: activeConnection ?? undefined,
      })

      const mappedUpdated: NamedQuery = {
        id: saved.id,
        name: saved.name,
        description: saved.description,
        query: saved.sqlTemplate,
        parameters: saved.params,
      }

      setNamedQueries((prev) => prev.map((q) => (q.id === mappedUpdated.id ? mappedUpdated : q)))

      // Update tabs that are using this named query
      setTabs((prevTabs) =>
        prevTabs.map((t) => {
          if (t.namedQueryId === mappedUpdated.id) {
            // Determine if we need to update params on the tab if interface changed?
            // For simplified UX, we'll keep existing params if possible, or reset if needed.
            // Here we just update the content/name.
            return {
              ...t,
              name: mappedUpdated.name,
              query: mappedUpdated.query
            }
          }
          return t
        })
      )

      toast({
        title: "Query updated",
        description: "Saved changes to named query."
      })

      scheduleAutoSyncNamedQueries()
    } catch (e: any) {
      console.error("Failed to update named query", e)
      toast({
        variant: "destructive",
        title: "Failed to update query",
        description: e?.message || "Could not save changes."
      })
    }
  }

  const handleSaveGenerator = async (tab: Tab, data: { name: string; description?: string }) => {
    if (!tab.generator) return
    const roles = tab.generator.mode === "update"
      ? tab.generator.params.reduce<Record<string, "set" | "where">>((acc, p) => {
        if (p.role) acc[p.name] = p.role
        return acc
      }, {})
      : undefined

    const sqlTemplate = encodeGeneratorTemplate({
      mode: tab.generator.mode,
      table: tab.generator.table,
      roles,
    })

    try {
      if (tab.namedQueryId) {
        const saved = await apiClient.namedQueries.update(tab.namedQueryId, {
          name: data.name,
          description: data.description,
          sqlTemplate,
          params: [],
          defaultConnectionId: activeConnection ?? undefined,
        })

        const mappedUpdated: NamedQuery = {
          id: saved.id,
          name: saved.name,
          description: saved.description,
          query: saved.sqlTemplate,
          parameters: saved.params,
        }

        setNamedQueries((prev) => prev.map((q) => (q.id === mappedUpdated.id ? mappedUpdated : q)))
        setTabs((prev) =>
          prev.map((t) =>
            t.id === tab.id ? { ...t, name: saved.name, namedQueryId: saved.id } : t,
          ),
        )
      } else {
        const saved = await apiClient.namedQueries.save({
          name: data.name,
          description: data.description,
          sqlTemplate,
          params: [],
          defaultConnectionId: activeConnection ?? undefined,
        })

        const newNamedQuery: NamedQuery = {
          id: saved.id,
          name: saved.name,
          description: saved.description,
          query: saved.sqlTemplate,
          parameters: saved.params,
        }

        setNamedQueries((prev) => [...prev, newNamedQuery])
        setTabs((prev) =>
          prev.map((t) =>
            t.id === tab.id ? { ...t, name: saved.name, namedQueryId: saved.id } : t,
          ),
        )
      }

      scheduleAutoSyncNamedQueries()
      toast({ title: "Saved generator" })
    } catch (e: any) {
      console.error("Failed to save generator", e)
      toast({
        variant: "destructive",
        title: "Failed to save generator",
        description: e?.message || "Could not save generator.",
      })
    }
  }

  const openNamedQueryTab = (nqId: string) => {
    const nq = namedQueries.find((q) => q.id === nqId)
    if (!nq) return

    const generatorMeta = decodeGeneratorTemplate(nq.query)
    if (generatorMeta) {
      openGeneratorTab(generatorMeta.mode, generatorMeta.table, nq, generatorMeta.roles)
      return
    }

    const existing = tabs.find((t) => t.namedQueryId === nq.id)
    if (existing) {
      setActiveTab(existing.id)
      return
    }

    const newId = `nq-tab-${Date.now()}`
    setTabs([...tabs, { id: newId, name: nq.name, query: nq.query, isNamedQuery: true, namedQueryId: nq.id, connectionId: activeConnection ?? undefined }])
    setActiveTab(newId)
  }

  const openGeneratorTab = (mode: GeneratorMode, table: { schema: string; name: string }, namedQuery?: NamedQuery, roles?: Record<string, "set" | "where">) => {
    if (!schema) {
      toast({
        variant: "destructive",
        title: "Schema not loaded",
        description: "Load schema before generating write queries.",
      })
      return
    }

    const params = buildGeneratorParams(schema, table, mode, roles)
    if (params.length === 0) {
      toast({
        variant: "destructive",
        title: "No columns found",
        description: "Unable to build generator for this table.",
      })
      return
    }

    const existing = namedQuery ? tabs.find((t) => t.namedQueryId === namedQuery.id) : null
    if (existing) {
      setActiveTab(existing.id)
      return
    }

    const newId = `gen-${Date.now()}`
    const newTab: Tab = {
      id: newId,
      name: namedQuery?.name ?? `${mode.toUpperCase()} ${table.name}`,
      query: "",
      isGenerator: true,
      namedQueryId: namedQuery?.id,
      generator: {
        mode,
        table,
        params,
      },
      connectionId: activeConnection ?? undefined,
    }

    setTabs([...tabs, newTab])
    setActiveTab(newId)
  }

  const handleJoinTables = async (baseTable: string, joins: JoinConfig[]) => {
    // Safety: quote identifiers to avoid breakage when table/column names are mixed-case or reserved words.
    const q = quoteIdent
    const base = q(baseTable)

    const joinClauses = joins
      .map((j) => {
        const leftTable = j.leftTable || baseTable
        const rightTable = j.table
        return `${j.joinType} JOIN ${q(rightTable)} ON ${q(leftTable)}.${q(j.leftColumn)} = ${q(rightTable)}.${q(j.rightColumn)}`
      })
      .join("\n")

    const joinQuery = `SELECT *\nFROM ${base}\n${joinClauses}`

    const joinNames = joins.map((j) => j.table).join(", ")
    const newId = `query-${Date.now()}`
    const newTab = { id: newId, name: `${baseTable} ⋈ ${joins.length > 1 ? `(${joins.length})` : joinNames}`, query: joinQuery, connectionId: activeConnection ?? undefined }
    setTabs([...tabs, newTab])
    setActiveTab(newId)

    // Auto-execute the join query
    if (activeConnection) {
      executeRawQuery(joinQuery, newId, activeConnection)
    }
  }

  const handleViewTable = (tableName: string) => {
    const currentTab = tabs.find((t) => t.id === activeTab)
    const currentQueryEmpty = !currentTab?.query?.trim()

    // tableName may be qualified ("schema.name") or bare ("name").
    const dotIdx = tableName.indexOf(".")
    const qualSchema = dotIdx >= 0 ? tableName.slice(0, dotIdx) : undefined
    const bareName = dotIdx >= 0 ? tableName.slice(dotIdx + 1) : tableName

    // Find primary key — prefer schema-qualified match, fall back to name-only.
    let orderByClause = ""
    if (schema?.primaryKeys) {
      const pk =
        (qualSchema
          ? schema.primaryKeys.find(
              (pk) => pk.table.schema === qualSchema && pk.table.name === bareName,
            )
          : undefined) ?? schema.primaryKeys.find((pk) => pk.table.name === bareName)
      if (pk) {
        orderByClause = `\nORDER BY ${quoteIdent(pk.columnName)} DESC`
      }
    }

    const query = `SELECT * FROM ${quoteIdent(tableName)}${orderByClause}`
    const pagination = { limit: 100, offset: 0 }

    if (currentTab && currentQueryEmpty) {
      setTabs((prev) =>
        prev.map((t) =>
          t.id === currentTab.id ? { ...t, query, pagination, name: `${bareName} (Top 100)` } : t,
        ),
      )
      if (activeConnection) {
        executeRawQuery(query, currentTab.id, activeConnection, 0, 100)
      }
      return
    }

    const normalizedQuery = query.trim()
    const matchesActiveConnection = (tab: Tab) =>
      activeConnection === null ? tab.connectionId === undefined : tab.connectionId === activeConnection
    const existingViewTab = tabs.find(
      (tab) => tab.query?.trim() === normalizedQuery && matchesActiveConnection(tab),
    )
    if (existingViewTab) {
      if (existingViewTab.id !== activeTab) {
        setActiveTab(existingViewTab.id)
      }
      if (activeConnection) {
        executeRawQuery(query, existingViewTab.id, activeConnection, 0, pagination.limit)
      }
      return
    }

    const newId = `view-${Date.now()}`
    const newTab = { id: newId, name: `${bareName} (Top 100)`, query, pagination, connectionId: activeConnection ?? undefined }
    setTabs([...tabs, newTab])
    setActiveTab(newId)

    if (activeConnection) {
      // Explicitly pass offset 0 and limit 100
      executeRawQuery(query, newId, activeConnection, 0, 100)
    }
  }



  const handleConnectionChange = (id: string) => {
    const previous = activeConnection
    // Set previous active to disconnected, new one to connected
    setConnections((prev) =>
      prev.map((c) => ({
        ...c,
        status: c.id === id ? "connected" : "disconnected",
      })),
    )
    setActiveConnection(id)
    // Release pools tied to the previous connection to avoid leaks when switching targets.
    if (previous && previous !== id) {
      void apiClient.connections.releasePools({ connectionId: previous }).catch(() => { })
    }
    void loadSchema(id)
  }

  const currentTab = tabs.find((t) => t.id === activeTab)
  const currentNamedQuery = currentTab?.namedQueryId
    ? namedQueries.find((nq) => nq.id === currentTab.namedQueryId)
    : null
  const currentGeneratorQuery = currentTab?.isGenerator ? buildGeneratorNamedQuery(currentTab) : null

  const currentResult = currentTab ? resultsByTab[currentTab.id] : undefined
  const currentParamLabels = currentTab?.query && currentTab.params ? deriveParamLabels(currentTab.query, currentTab.params.length) : []

  // loadSchema defined above with useCallback

  async function executeRawQuery(sqlArg?: string, tabIdArg?: string, connectionIdArg?: string, newOffset: number = 0, newLimit?: number | null) {
    const targetTabId = tabIdArg || activeTab
    const targetTab = tabs.find(t => t.id === targetTabId)
    const targetConnectionId = connectionIdArg || targetTab?.connectionId || activeConnection

    if (!targetConnectionId) return

    const offset = newOffset
    const paramValues = (targetTab?.params ?? []).map((p) => {
      if (p.type === "number") return Number(p.value)
      if (p.type === "boolean") return p.value === "true"
      return p.value
    })

    // Resolve SQL: Argument -> Current Tab -> Empty
    let sql = sqlArg
    if (!sql) {
      sql = targetTab?.query || ""
    }
    // Support users who wrap $n in quotes; strip the quotes for execution while keeping param order.
    const sqlToRun = cleanPositionalPlaceholders(sql)

    if (!sqlToRun.trim()) return

    // Strict Read-Only Check
    if (!isReadOnlySql(sqlToRun)) {
      toast({
        variant: "destructive",
        title: "Query Rejected",
        description: "Only read-only queries (SELECT, WITH) are allowed prevention initiated by client console."
      })
      return
    }

    setIsRunning(true)
    setError(null)
    // If this tab had an open stream, tear it down — running a new query
    // means the previous stream is no longer interesting, and leaving it
    // open holds a Postgres client checked out indefinitely.
    void closeStreamForTab(targetTabId)

    try {
      // Clean SQL for wrapping (remove trailing semicolon)
      const cleanSql = sqlToRun.trim().replace(/;+$/, "")
      const hasUserLimit = hasLimitClause(cleanSql)
      const fallbackLimit = hasUserLimit ? undefined : targetTab?.pagination?.limit ?? 100
      const limit = newLimit === undefined ? fallbackLimit : newLimit === null ? undefined : newLimit

      const shouldIncludeCount = offset === 0 || targetTab?.pagination?.total === undefined

      const data = await apiClient.query.run({
        kind: "raw",
        sql: cleanSql,
        originalSql: cleanSql,
        connectionId: targetConnectionId,
        poolMode,
        scopeKey: poolMode === "per-scope" ? targetTabId : undefined,
        params: paramValues,
        limit,
        offset,
        includeCount: shouldIncludeCount,
      })

      const sqlDisplay = renderSqlWithParams(cleanSql, paramValues)
      setResultsByTab((prev) => ({ ...prev, [targetTabId]: { ...data, sqlDisplay } }))

      // Show success toast with metrics
      toast({
        title: "Query executed",
        description: `${data.rows.length} rows • ${data.durationMs}ms`,
      })

      // Update tab pagination state
      setTabs(prev => prev.map(t => {
        if (t.id === targetTabId) {
          return {
            ...t,
            connectionId: targetConnectionId,
            pagination: {
              limit,
              offset,
              total: data.totalCount ?? t.pagination?.total ?? data.rows?.length
            }
          }
        }
        return t
      }))

    } catch (e: any) {
      console.error("Failed to run query", e)
      const detail = asQueryErrorBody(e)
      setError(detail?.error ?? e?.message ?? "Failed to run query")
      toast({
        variant: "destructive",
        title: "Query failed",
        description: detail?.error ?? e?.message ?? "Failed to run query",
      })
    } finally {
      setIsRunning(false)
    }
  }

  // ---- Streaming -----------------------------------------------------------
  //
  // When a bounded query gets clipped to DBCONSOLE_MAX_ROWS the user can opt
  // into streaming via the truncation banner. We re-run the same SQL through
  // /api/query/stream/open, replace the bounded result with the first batch,
  // and let "Load more" pull subsequent batches via /next. The stream is held
  // open server-side until the user closes it, runs a new query in the same
  // tab, or closes the tab.

  const closeStreamForTab = useCallback(async (tabId: string) => {
    const stream = streamsByTab[tabId]
    if (!stream) return
    try {
      await apiClient.query.stream.close({ streamId: stream.streamId })
    } catch (e) {
      console.error("Failed to close stream", e)
    }
    setStreamsByTab((prev) => {
      const next = { ...prev }
      delete next[tabId]
      return next
    })
  }, [streamsByTab])

  async function startStreamForTab(targetTabId: string) {
    const tab = tabs.find((t) => t.id === targetTabId)
    if (!tab) return
    const targetConnectionId = tab.connectionId ?? activeConnection
    if (!targetConnectionId) return

    // Tear down any existing stream for this tab before starting a new one.
    await closeStreamForTab(targetTabId)

    setIsRunning(true)
    setError(null)

    try {
      const cleanSql = (tab.query ?? "").trim().replace(/;+$/, "")
      const result = await apiClient.query.stream.open({
        query: {
          kind: "raw",
          sql: cleanSql,
          originalSql: cleanSql,
          connectionId: targetConnectionId,
          poolMode,
          scopeKey: poolMode === "per-scope" ? targetTabId : undefined,
        },
      })

      // Replace the bounded result with the streamed first batch. truncated is
      // explicitly false because the streaming UI carries its own affordances.
      setResultsByTab((prev) => ({
        ...prev,
        [targetTabId]: {
          columns: result.columns,
          rows: result.rows,
          durationMs: 0,
          sqlDisplay: cleanSql,
          truncated: false,
          truncatedAt: undefined,
          requestedLimit: undefined,
        },
      }))

      setStreamsByTab((prev) => ({
        ...prev,
        [targetTabId]: {
          streamId: result.streamId,
          rowsSent: result.rowsSent,
          hasMore: result.hasMore,
          loading: false,
        },
      }))

      toast({
        title: "Streaming started",
        description: `${result.rows.length} rows in first batch`,
      })
    } catch (e: any) {
      console.error("Failed to open stream", e)
      const detail = asQueryErrorBody(e)
      setError(detail?.error ?? e?.message ?? "Failed to open stream")
      toast({
        variant: "destructive",
        title: "Stream failed",
        description: detail?.error ?? e?.message ?? "Failed to open stream",
      })
    } finally {
      setIsRunning(false)
    }
  }

  async function loadMoreForStream(targetTabId: string) {
    const stream = streamsByTab[targetTabId]
    if (!stream || !stream.hasMore || stream.loading) return

    setStreamsByTab((prev) => ({
      ...prev,
      [targetTabId]: prev[targetTabId] ? { ...prev[targetTabId]!, loading: true } : prev[targetTabId],
    }))

    try {
      const result = await apiClient.query.stream.next({ streamId: stream.streamId })
      setResultsByTab((prev) => {
        const cur = prev[targetTabId]
        if (!cur) return prev
        return {
          ...prev,
          [targetTabId]: { ...cur, rows: [...cur.rows, ...result.rows] },
        }
      })
      setStreamsByTab((prev) => ({
        ...prev,
        [targetTabId]: prev[targetTabId]
          ? { ...prev[targetTabId]!, rowsSent: result.rowsSent, hasMore: result.hasMore, loading: false }
          : prev[targetTabId],
      }))
    } catch (e: any) {
      console.error("Failed to fetch next batch", e)
      const detail = asQueryErrorBody(e)
      setError(detail?.error ?? e?.message ?? "Stream fetch failed")
      // The server already torn down the stream on a fetch error; clear state.
      setStreamsByTab((prev) => {
        const next = { ...prev }
        delete next[targetTabId]
        return next
      })
    }
  }

  async function executeNamedQuery(query: NamedQuery, params: Record<string, string>, newOffset: number = 0, newLimit?: number | null) {
    if (!activeConnection) return
    const targetTab = currentTab
    const offset = newOffset
    // We only need to know whether the user's SQL already has a LIMIT clause to decide
    // whether to apply our own pagination limit. This can be determined from the template
    // itself; parameter substitution happens server-side.
    const hasUserLimit = hasLimitClause(query.query)
    const fallbackLimit = hasUserLimit ? undefined : targetTab?.pagination?.limit ?? 100
    const limit = newLimit === undefined ? fallbackLimit : newLimit === null ? undefined : newLimit
    setIsRunning(true)
    setError(null)
    if (currentTab) void closeStreamForTab(currentTab.id)

    try {
      const shouldIncludeCount = offset === 0 || targetTab?.pagination?.total === undefined

      const data = await apiClient.query.run({
        kind: "named",
        queryId: query.id,
        params,
        connectionId: activeConnection,
        poolMode,
        scopeKey: poolMode === "per-scope" ? currentTab?.id : undefined,
        limit,
        offset,
        originalSql: query.query,
        includeCount: shouldIncludeCount,
      })

      if (currentTab) {
        // For display, substitute :param occurrences with literals in the template
        const sqlDisplay = Object.entries(params).reduce((acc, [key, value]) => {
          const literal = toSqlLiteral(value)
          // Only replace real named params; avoid matching MACs/hex segments after ':'.
          const pattern = new RegExp(`(^|[^0-9A-Za-z_]):${escapeRegex(key)}\\b`, "g")
          return acc.replace(pattern, (_m, prefix) => `${prefix}${literal}`)
        }, query.query)
        setResultsByTab((prev) => ({ ...prev, [currentTab.id]: { ...data, sqlDisplay } }))

        // Show success toast with metrics
        toast({
          title: "Query executed",
          description: `${data.rows.length} rows • ${data.durationMs}ms`,
        })

        setTabs(prev => prev.map(t => {
          if (t.id === currentTab.id) {
            return {
              ...t,
              connectionId: activeConnection,
              namedParams: params,
              pagination: {
                limit,
                offset,
                total: data.totalCount ?? t.pagination?.total ?? data.rows?.length
              }
            }
          }
          return t
        }))
      }
    } catch (e: any) {
      console.error("Failed to run named query", e)
      const detail = asQueryErrorBody(e)
      setError(detail?.error ?? e?.message ?? "Failed to run named query")
      toast({
        variant: "destructive",
        title: "Query failed",
        description: detail?.error ?? e?.message ?? "Failed to run query",
      })
    } finally {
      setIsRunning(false)
    }
  }

  const updateGeneratorParamValues = (tabId: string, values: Record<string, string>) => {
    setTabs((prev) =>
      prev.map((t) => {
        if (t.id !== tabId || !t.generator) return t
        const nextParams = t.generator.params.map((p) => ({
          ...p,
          value: values[p.name] ?? "",
        }))
        return { ...t, generator: { ...t.generator, params: nextParams } }
      }),
    )
  }

  const updateGeneratorParamMeta = (tabId: string, name: string, updates: Partial<GeneratorParamState>) => {
    setTabs((prev) =>
      prev.map((t) => {
        if (t.id !== tabId || !t.generator) return t
        const nextParams = t.generator.params.map((p) => (p.name === name ? { ...p, ...updates } : p))
        return { ...t, generator: { ...t.generator, params: nextParams } }
      }),
    )
  }

  const generateForTab = (tab: Tab, overrideValues?: Record<string, string>) => {
    if (!tab.generator) return
    const generatorConfig: GeneratorConfig = overrideValues
      ? {
        ...tab.generator,
        params: tab.generator.params.map((p) => ({ ...p, value: overrideValues[p.name] ?? p.value })),
      }
      : tab.generator
    const { sql, warnings } = generateWriteSql(generatorConfig)

    setError(null)

    if (warnings.includes("No SET values provided.")) {
      toast({
        variant: "destructive",
        title: "Nothing to update",
        description: "Add at least one SET value before generating.",
      })
      return
    }
    if (warnings.includes("No WHERE values provided.")) {
      toast({
        variant: "destructive",
        title: "Missing WHERE clause",
        description: "Mark at least one column as WHERE to generate a safe UPDATE.",
      })
      return
    }

    const row = { "Generated SQL": sql }
    setResultsByTab((prev) => ({
      ...prev,
      [tab.id]: { columns: ["Generated SQL"], rows: [row], durationMs: 0, sqlDisplay: sql },
    }))
  }

  // Handle show/hide query toggle - persist to tab
  const handleShowQueryChange = useCallback((shown: boolean) => {
    // Persist to tab state
    if (activeTab) {
      setTabs(prev => prev.map(t => t.id === activeTab ? { ...t, showQuery: shown } : t))
    }
  }, [activeTab])

  // Handle params expand/collapse - global state
  const handleParamsExpandChange = useCallback((expanded: boolean) => {
    // Update global state
    setGlobalParamsExpanded(expanded)
  }, [])

  return (
    <>
      <div className="h-full w-full bg-background flex flex-col overflow-hidden">
        {/* Header with tabs and settings */}
        <div className="flex items-center justify-between border-b border-border bg-background px-2 py-2">
          <div className="flex items-center gap-2 flex-1 min-w-0">
            <Button
              variant="ghost"
              size="icon"
              className="h-8 w-8 text-muted-foreground hover:text-foreground flex-shrink-0"
              onClick={() => setSidebarOpen(!sidebarOpen)}
            >
              <PanelLeft className="h-4 w-4" />
            </Button>
            <QueryTabs
              tabs={tabs}
              activeTab={activeTab}
              onTabChange={setActiveTab}
              onTabClose={closeTab}
              onAddTab={addTab}
              onTabReorder={reorderTabs}
            />
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            <Button
              variant="ghost"
              size="sm"
              className="h-8 gap-1.5 text-muted-foreground hover:text-foreground"
              onClick={() => setShowGenerateDialog(true)}
            >
              <Sparkles className="h-4 w-4 text-emerald-600" />
              Generate
            </Button>
            <Button
              variant="ghost"
              size="icon"
              className="h-8 w-8 text-muted-foreground hover:text-foreground"
              onClick={() => setShowConnectionDialog(true)}
            >
              <Settings className="h-4 w-4" />
            </Button>
          </div>
        </div>

        {/* Main content area */}
        <div className="flex flex-1 overflow-hidden">
          <ResizablePanelGroup direction="horizontal">
            {/* Collapsible sidebar */}
            {sidebarOpen && (
              <>
                <ResizablePanel defaultSize={15} minSize={15} maxSize={40} className="border-r border-border bg-background">
                  <div className="h-full flex flex-col">
                    <div className="flex-1 p-3 overflow-hidden">
                      <SchemasSidebar
                        connections={connections}
                        activeConnection={activeConnection}
                        onConnectionChange={handleConnectionChange}
                        namedQueries={namedQueries.map((nq) => ({ id: nq.id, name: nq.name }))}
                        onOpenNamedQuery={openNamedQueryTab}
                        onDeleteNamedQuery={async (id) => {
                          try {
                            await apiClient.namedQueries.delete(id)
                            setNamedQueries((prev) => prev.filter((nq) => nq.id !== id))
                            // Close any open tabs for this query
                            setTabs((prev) => prev.filter((t) => t.namedQueryId !== id))
                            toast({ title: "Query deleted" })
                          } catch (e: any) {
                            toast({
                              variant: "destructive",
                              title: "Failed to delete query",
                              description: e?.message,
                            })
                          }
                        }}
                        onJoinTables={handleJoinTables}
                        onViewTable={handleViewTable}
                        onOpenSql={openSqlInNewTab}
                        onOpenSettings={() => setShowConnectionDialog(true)}
                        onOpenSyncSettings={() => setShowSyncSettingsDialog(true)}
                        onSyncNamedQueries={handleSyncNamedQueries}
                        showActionsOnHover={sidebarActionsShowOnHover}
                        onRefreshSchema={() => {
                          if (activeConnection) {
                            void loadSchema(activeConnection)
                          }
                        }}
                        schema={schema}
                        activeTab={sidebarTab}
                        onActiveTabChange={setSidebarTab}
                        onFocusQuery={() => {
                          // Focus the SQL editor after a brief delay to let state update
                          setTimeout(() => {
                            const editorEl = document.getElementById("sql-editor-main")
                            if (editorEl) {
                              const cmContent = editorEl.querySelector(".cm-content") as HTMLElement
                              cmContent?.focus()
                            }
                          }, 50)
                        }}
                      />
                    </div>
                  </div>
                </ResizablePanel>
                <ResizableHandle />
              </>
            )}

            {/* Query and results area */}
            <ResizablePanel defaultSize={95}>
              {currentTab?.isSchemaGraph ? (
                <SchemaGraphView
                  schema={schema}
                  onRefresh={() => {
                    if (activeConnection) void loadSchema(activeConnection)
                  }}
                />
              ) : (
              <div className="h-full flex flex-col overflow-hidden">
                <ResizablePanelGroup direction="vertical">
                  {/* Query editor section */}
                  <ResizablePanel
                    defaultSize={20}
                    minSize={20}
                    className="flex flex-col"
                  >
                    <div className="flex-1 min-h-0 relative">
                      {currentTab?.isGenerator && currentGeneratorQuery ? (
                        <NamedQueryEditor
                          key={`${currentTab.id}:${currentGeneratorQuery.id}`}
                          namedQuery={currentGeneratorQuery}
                          mode="generator"
                          onExecute={(_query, params) => {
                            if (!currentTab) return
                            updateGeneratorParamValues(currentTab.id, params)
                            generateForTab(currentTab, params)
                          }}
                          onEdit={() => { }}
                          onSaveGenerator={() => {
                            if (!currentTab) return
                            setSavingGeneratorTab(currentTab)
                            setShowSaveGeneratorDialog(true)
                          }}
                          generatedSql={currentResult?.sqlDisplay}
                          onCopyGeneratedSql={() => {
                            if (!currentResult?.sqlDisplay) return
                            navigator.clipboard.writeText(currentResult.sqlDisplay)
                            toast({ title: "Generated SQL copied" })
                          }}
                          paramsExpanded={globalParamsExpanded}
                          onParamsExpandChange={handleParamsExpandChange}
                          paramValues={currentTab.generator?.params.reduce<Record<string, string>>((acc, p) => {
                            acc[p.name] = p.value
                            return acc
                          }, {})}
                          onParamValuesChange={(next) => currentTab && updateGeneratorParamValues(currentTab.id, next)}
                          paramMeta={buildGeneratorParamMeta(currentTab)}
                          onParamMetaChange={(name, updates) => currentTab && updateGeneratorParamMeta(currentTab.id, name, updates)}
                        />
                      ) : currentTab?.isNamedQuery && currentNamedQuery ? (
                        <NamedQueryEditor
                          key={`${currentNamedQuery.id}:${currentNamedQuery.query}:${currentNamedQuery.parameters.map((p) => `${p.name}:${p.defaultValue ?? ""}`).join("|")}`}
                          namedQuery={currentNamedQuery}
                          onExecute={executeNamedQuery}
                          onEdit={() => {
                            setEditingNamedQuery(currentNamedQuery)
                            setShowSaveNamedDialog(true)
                          }}
                          paramsExpanded={globalParamsExpanded}
                          onParamsExpandChange={handleParamsExpandChange}
                        />
                      ) : (
                        <QueryEditor
                          query={currentTab?.query || ""}
                          onChange={(q) => currentTab && updateQuery(currentTab.id, q)}
                          onRun={() => executeRawQuery(undefined, undefined, activeConnection ?? undefined, 0)}
                          onSaveAsNamed={() => setShowSaveNamedDialog(true)}
                          schema={schema}
                          params={currentTab?.params}
                          paramLabels={currentParamLabels}
                          onParamsChange={(p) => currentTab && updateParams(currentTab.id, p)}
                        />
                      )}
                    </div>
                  </ResizablePanel>

                  <ResizableHandle className="h-px bg-border" />

                  {/* Data grid section */}
                  <ResizablePanel defaultSize={60} minSize={20}>
                    <div className="h-full overflow-hidden border-t border-border flex flex-col">
                      {currentResult ? (
                        currentTab && (
                          <DataGrid
                            columns={currentResult?.columns || []}
                            data={currentResult?.rows || []}
                            loading={isRunning}
                            error={error}
                            truncated={
                              currentResult?.truncated
                                ? {
                                  at: currentResult.truncatedAt ?? currentResult.rows.length,
                                  requestedLimit: currentResult.requestedLimit,
                                  onSwitchToStream: currentTab && !currentTab.isNamedQuery && !currentTab.isGenerator
                                    ? () => { void startStreamForTab(currentTab.id) }
                                    : undefined,
                                }
                                : null
                            }
                            streaming={
                              currentTab && streamsByTab[currentTab.id]
                                ? {
                                  rowsSent: streamsByTab[currentTab.id]!.rowsSent,
                                  hasMore: streamsByTab[currentTab.id]!.hasMore,
                                  loading: streamsByTab[currentTab.id]!.loading,
                                  onLoadMore: () => { void loadMoreForStream(currentTab.id) },
                                  onClose: () => { void closeStreamForTab(currentTab.id) },
                                }
                                : null
                            }
                            executedSql={currentResult?.sqlDisplay}
                            pagination={currentTab.pagination}
                            onPageChange={(newOffset) => {
                              if (currentTab.isGenerator) {
                                return
                              }
                              if (currentTab.isNamedQuery && currentNamedQuery) {
                                executeNamedQuery(currentNamedQuery, currentTab.namedParams ?? {}, newOffset)
                              } else {
                                executeRawQuery(undefined, currentTab.id, currentTab.connectionId ?? activeConnection ?? undefined, newOffset)
                              }
                            }}
                            onLimitChange={(newLimit) => {
                              if (currentTab.isGenerator) {
                                return
                              }
                              if (currentTab.isNamedQuery && currentNamedQuery) {
                                executeNamedQuery(currentNamedQuery, currentTab.namedParams ?? {}, 0, newLimit)
                              } else {
                                executeRawQuery(undefined, currentTab.id, currentTab.connectionId ?? activeConnection ?? undefined, 0, newLimit)
                              }
                            }}
                          />
                        )
                      ) : (
                        <div className="flex h-full flex-col items-center justify-center text-muted-foreground gap-2">
                          {/* Empty state content */}
                          <div className="h-10 w-10 rounded-full bg-secondary flex items-center justify-center">
                            <svg className="h-5 w-5 text-muted-foreground" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                              <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 9.776c.112-.017.227-.026.344-.026h15.812c.117 0 .232.009.344.026m-16.5 0a2.25 2.25 0 00-1.883 2.542l.857 6a2.25 2.25 0 002.227 1.932H19.05a2.25 2.25 0 002.227-1.932l.857-6a2.25 2.25 0 00-1.883-2.542m-16.5 0V6A2.25 2.25 0 016 3.75h3.879a1.5 1.5 0 011.06.44l2.122 2.12a1.5 1.5 0 001.06.44H18A2.25 2.25 0 0120.25 9v.776" />
                            </svg>
                          </div>
                          <span className="text-sm font-medium">{isRunning ? "Running query..." : "Run a query to see results"}</span>
                          <span className="text-xs text-muted-foreground">Press ⌘+Enter to execute</span>
                        </div>
                      )}
                    </div>
                  </ResizablePanel>
                </ResizablePanelGroup>
              </div>
              )}
            </ResizablePanel>
          </ResizablePanelGroup>
        </div>
      </div>

      <GenerateWriteQueryDialog
        open={showGenerateDialog}
        onOpenChange={setShowGenerateDialog}
        tables={schema?.tables ?? []}
        onGenerate={(mode: WriteQueryMode, table) => {
          openGeneratorTab(mode, table)
        }}
      />

      <SlowQueryPanel
        open={showSlowQueries}
        onOpenChange={setShowSlowQueries}
        connectionId={activeConnection}
        onOpenInTab={(sql) => {
          openSqlInNewTab(sql, "Slow query")
          setShowSlowQueries(false)
        }}
      />

      <QueryHistoryPanel
        open={showQueryHistory}
        onOpenChange={setShowQueryHistory}
        connections={connections.map((c) => ({ id: c.id, label: c.label }))}
        defaultConnectionId={activeConnection}
        onOpenInTab={(sql) => {
          openSqlInNewTab(sql, "From history")
          setShowQueryHistory(false)
        }}
      />

      <ConnectionDialog
        open={showConnectionDialog}
        onOpenChange={setShowConnectionDialog}
        connections={connections}
        activeConnection={activeConnection}
        poolMode={poolMode}
        onConnectionsChange={(updated) => {
          setConnections((prev) => {
            const statusById = new Map(prev.map((c) => [c.id, c.status]))
            return updated.map((c) => ({
              ...c,
              status: statusById.get(c.id) ?? "disconnected",
            }))
          })
        }}
        onConnect={(id) => {
          handleConnectionChange(id)
        }}
        onPoolModeChange={(mode) => setPoolMode(mode)}
      />

      <SyncSettingsDialog
        open={showSyncSettingsDialog}
        onOpenChange={setShowSyncSettingsDialog}
        onSaved={() => {
          toast({ title: "Sync settings saved" })
          void handleSyncNamedQueries()
        }}
        onCleared={() => {
          toast({ title: "Sync disabled on this device" })
        }}
      />

      {syncConflicts && (
        <NamedQuerySyncConflictsDialog
          open={showSyncConflictsDialog}
          onOpenChange={setShowSyncConflictsDialog}
          conflicts={syncConflicts as any}
          onApply={applySyncResolutions}
        />
      )}

      <SaveNamedQueryDialog
        key={`${showSaveNamedDialog ? "open" : "closed"}:${editingNamedQuery?.id ?? "new"}:${editingNamedQuery ? "edit" : "create"}`}
        open={showSaveNamedDialog}
        onOpenChange={(open) => {
          setShowSaveNamedDialog(open)
          if (!open) setEditingNamedQuery(null)
        }}
        query={editingNamedQuery ? editingNamedQuery.query : (currentTab?.query || "")}
        mode={editingNamedQuery ? "edit" : "create"}
        initialValues={editingNamedQuery ? {
          name: editingNamedQuery.name,
          description: editingNamedQuery.description,
          parameters: editingNamedQuery.parameters
        } : undefined}
        onSave={(data) => {
          if (editingNamedQuery) {
            void handleUpdateNamedQuery({ ...data, id: editingNamedQuery.id })
          } else {
            void handleSaveAsNamed(data)
          }
        }}
      />

      <SaveGeneratorDialog
        open={showSaveGeneratorDialog}
        onOpenChange={(open) => {
          setShowSaveGeneratorDialog(open)
          if (!open) setSavingGeneratorTab(null)
        }}
        mode={savingGeneratorTab?.namedQueryId ? "edit" : "create"}
        initialValues={
          savingGeneratorTab
            ? {
              name: savingGeneratorTab.name,
              description: savingGeneratorTab.namedQueryId
                ? namedQueries.find((nq) => nq.id === savingGeneratorTab.namedQueryId)?.description
                : undefined,
            }
            : undefined
        }
        onSave={(data) => {
          if (!savingGeneratorTab) return
          void handleSaveGenerator(savingGeneratorTab, data)
        }}
      />

      <CommandDialog open={commandPaletteOpen} onOpenChange={setCommandPaletteOpen}>
        <CommandInput placeholder="Type a command…" />
        <CommandList>
          <CommandEmpty>No results.</CommandEmpty>
          {Object.entries(
            listCommands().reduce((acc, cmd) => {
              const cat = cmd.category ?? "Other"
              acc[cat] = acc[cat] ?? []
              acc[cat].push(cmd)
              return acc
            }, {} as Record<string, ReturnType<typeof listCommands>>),
          ).map(([category, cmds], idx) => (
            <div key={category}>
              {idx > 0 && <CommandSeparator />}
              <CommandGroup heading={category}>
                {cmds.map((cmd) => {
                  const state = shortcuts.getCommandState(cmd.id)
                  const raw = state.displayBinding
                  const parsed = raw ? parseBinding(raw) : null
                  const isMac = typeof navigator !== "undefined" ? /mac/i.test(navigator.platform) : false
                  const label = parsed ? formatBinding(parsed, shortcuts.runtime, { isMac }) : undefined
                  return (
                    <CommandItem
                      key={cmd.id}
                      value={`${cmd.title} ${cmd.id}`}
                      onSelect={() => {
                        shortcuts.invoke(cmd.id)
                        setCommandPaletteOpen(false)
                      }}
                    >
                      <span className="truncate">{cmd.title}</span>
                      {label && (
                        <CommandShortcut
                          className={cn(
                            state.isDisabled &&
                              "text-destructive border border-destructive/50 rounded-sm px-1 py-0.5",
                          )}
                        >
                          {label}
                        </CommandShortcut>
                      )}
                    </CommandItem>
                  )
                })}
              </CommandGroup>
            </div>
          ))}
        </CommandList>
      </CommandDialog>

      <MenuHandler />
    </>
  )
}
