"use client"

import { useState, useRef, useCallback, useMemo } from "react"
import { ChevronRight, Table2, Search, Bookmark, GitMerge, X, Plus, ChevronDown, Eye, RotateCcw, KeyRound, Database } from "lucide-react"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu"
import { JoinBuilderDialog } from "./join-builder-dialog"
import type { SchemaGraph } from "@/lib/schema-introspection"
import { isAutoGeneratedColumn } from "@/lib/schema-utils"

interface TableInfo {
  name: string
  schema: string
  qualifiedName: string
  /** What kind of relation this is — drives the icon and badge in the tree. */
  kind: "table" | "view" | "matview"
  columns: {
    name: string;
    type: string;
    isFk?: boolean;
    isPk?: boolean;
    isAuto?: boolean;
    references?: { schema: string; table: string; qualifiedTable: string; column: string }
  }[]
  indexes: {
    name: string
    isUnique: boolean
    isPrimary: boolean
    columns: string[]
    definition: string
  }[]
  triggers: {
    name: string
    timing: string
    events: string[]
    definition: string
  }[]
}

interface NamedQuery {
  id: string
  name: string
}

interface Connection {
  id: string
  label: string
  status?: "connected" | "connecting" | "disconnected"
}

interface JoinConfig {
  table: string
  leftColumn: string
  rightColumn: string
  joinType: "INNER" | "LEFT" | "RIGHT" | "FULL"
}

interface SchemasSidebarProps {
  connections: Connection[]
  activeConnection: string | null
  onConnectionChange: (id: string) => void
  namedQueries: NamedQuery[]
  onOpenNamedQuery: (id: string) => void
  onDeleteNamedQuery?: (id: string) => void
  onJoinTables: (baseTable: string, joins: JoinConfig[]) => void
  onViewTable: (tableName: string) => void
  /** Open arbitrary SQL in a new tab — used by the routines list. */
  onOpenSql?: (sql: string, name?: string) => void
  onOpenSettings: () => void
  onSyncNamedQueries?: () => void
  onOpenSyncSettings?: () => void
  onRefreshSchema?: () => void
  showActionsOnHover?: boolean
  schema?: SchemaGraph | null
  activeTab?: "tables" | "queries"
  onActiveTabChange?: (tab: "tables" | "queries") => void
  onFocusQuery?: () => void
}

export function SchemasSidebar({
  connections,
  activeConnection,
  onConnectionChange,
  namedQueries,
  onOpenNamedQuery,
  onDeleteNamedQuery,
  onJoinTables,
  onViewTable,
  onOpenSql,
  onOpenSettings,
  onSyncNamedQueries,
  onOpenSyncSettings,
  onRefreshSchema,
  showActionsOnHover = true,
  schema,
  activeTab: activeTabProp,
  onActiveTabChange,
  onFocusQuery,
}: SchemasSidebarProps) {
  const [search, setSearch] = useState("")
  const [expandedTables, setExpandedTables] = useState<Set<string>>(new Set())
  const [collapsedSchemas, setCollapsedSchemas] = useState<Set<string>>(new Set())
  const [activeTabState, setActiveTabState] = useState<"tables" | "queries">("tables")
  const [joinDialogOpen, setJoinDialogOpen] = useState(false)
  const [joinBaseTable, setJoinBaseTable] = useState<string>("")
  const activeTab = activeTabProp ?? activeTabState
  const setActiveTab = (tab: "tables" | "queries") => {
    if (onActiveTabChange) onActiveTabChange(tab)
    else setActiveTabState(tab)
  }

  // Refs for keyboard navigation
  const tableListRef = useRef<HTMLDivElement>(null)
  const queryListRef = useRef<HTMLDivElement>(null)
  const searchInputRef = useRef<HTMLInputElement>(null)

  // Keyboard navigation helper
  const handleListKeyDown = useCallback((
    e: React.KeyboardEvent,
    itemSelector: string,
    currentIndex: number,
    totalItems: number
  ) => {
    if (e.key === "ArrowDown") {
      e.preventDefault()
      const nextIndex = Math.min(currentIndex + 1, totalItems - 1)
      const nextItem = document.querySelector(`[${itemSelector}="${nextIndex}"]`) as HTMLElement
      nextItem?.focus()
    } else if (e.key === "ArrowUp") {
      e.preventDefault()
      if (currentIndex === 0) {
        // Focus search input when at top
        searchInputRef.current?.focus()
      } else {
        const prevIndex = currentIndex - 1
        const prevItem = document.querySelector(`[${itemSelector}="${prevIndex}"]`) as HTMLElement
        prevItem?.focus()
      }
    }
  }, [])

  const toggleTable = (key: string) => {
    const next = new Set(expandedTables)
    if (next.has(key)) {
      next.delete(key)
    } else {
      next.add(key)
    }
    setExpandedTables(next)
  }

  const toggleSchema = (schemaName: string) => {
    const next = new Set(collapsedSchemas)
    if (next.has(schemaName)) {
      next.delete(schemaName)
    } else {
      next.add(schemaName)
    }
    setCollapsedSchemas(next)
  }

  const searchLower = search.toLowerCase()

  // Iterate over the unified relations list (tables + views + matviews) so the
  // tree shows everything you can SELECT FROM, not just base tables. Falls back
  // to schema.tables for older payloads where relations isn't populated.
  const sourceRelations = schema?.relations
    ?? schema?.tables.map((t) => ({ ...t, kind: 'table' as const }))
    ?? []

  const tables: TableInfo[] = schema
    ? sourceRelations.map((t) => ({
      name: t.name,
      schema: t.schema,
      qualifiedName: `${t.schema}.${t.name}`,
      kind: t.kind,
      columns:
        schema.columns
          .filter((c) => c.table.schema === t.schema && c.table.name === t.name)
          .map((c) => {
            const fk = schema.foreignKeys.find(
              (fk) =>
                fk.from.schema === t.schema &&
                fk.from.name === t.name &&
                fk.fromColumn === c.name,
            )
            const pk = schema.primaryKeys.find(
              (pk) =>
                pk.table.schema === t.schema &&
                pk.table.name === t.name &&
                pk.columnName === c.name,
            )
            return {
              name: c.name,
              type: c.dataType,
              isFk: !!fk,
              isPk: !!pk,
              isAuto: isAutoGeneratedColumn(c),
              references: fk
                ? {
                  schema: fk.to.schema,
                  table: fk.to.name,
                  qualifiedTable: `${fk.to.schema}.${fk.to.name}`,
                  column: fk.toColumn,
                }
                : undefined,
            }
          }) ?? [],
      indexes: (schema.indexes ?? [])
        .filter((idx) => idx.table.schema === t.schema && idx.table.name === t.name && !idx.isPrimary)
        .map((idx) => ({
          name: idx.name,
          isUnique: idx.isUnique,
          isPrimary: idx.isPrimary,
          columns: idx.columns,
          definition: idx.definition,
        })),
      triggers: (schema.triggers ?? [])
        .filter((trg) => trg.table.schema === t.schema && trg.table.name === t.name)
        .map((trg) => ({
          name: trg.name,
          timing: trg.timing,
          events: trg.events,
          definition: trg.definition,
        })),
    }))
    : []

  const filteredTables = tables.filter(
    (t) =>
      t.name.toLowerCase().includes(searchLower) ||
      t.schema.toLowerCase().includes(searchLower),
  )
  const filteredQueries = namedQueries.filter((q) => q.name.toLowerCase().includes(searchLower))

  // Group filtered tables by schema. Sort schemas with "public" first, then alpha.
  const groupedTables = useMemo(() => {
    const groups = new Map<string, TableInfo[]>()
    for (const t of filteredTables) {
      const arr = groups.get(t.schema) ?? []
      arr.push(t)
      groups.set(t.schema, arr)
    }
    return Array.from(groups.entries()).sort(([a], [b]) => {
      if (a === b) return 0
      if (a === "public") return -1
      if (b === "public") return 1
      return a.localeCompare(b)
    })
  }, [filteredTables])

  const hasMultipleSchemas = groupedTables.length > 1

  // While searching, force-expand all schema groups so matches are visible.
  const isSearching = search.trim().length > 0

  // Flat index across visible items for keyboard navigation
  const flatTableEntries = useMemo(() => {
    const out: TableInfo[] = []
    for (const [schemaName, group] of groupedTables) {
      if (!isSearching && hasMultipleSchemas && collapsedSchemas.has(schemaName)) continue
      out.push(...group)
    }
    return out
  }, [groupedTables, collapsedSchemas, isSearching, hasMultipleSchemas])

  const activeConn = connections.find((c) => c.id === activeConnection)

  const getStatusColor = (status?: string) => {
    switch (status) {
      case "connected":
        return "bg-emerald-400"
      case "connecting":
        return "bg-amber-400"
      default:
        return "bg-muted-foreground/40"
    }
  }

  const openJoinBuilder = (tableName: string) => {
    setJoinBaseTable(tableName)
    setJoinDialogOpen(true)
  }

  return (
    <div className="flex h-full flex-col">
      {/* Top controls */}
      <div className="space-y-2">
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <button
              className={cn(
                "group flex h-9 w-full items-center gap-2 rounded-md border border-border bg-background/70 px-2 text-left text-sm text-foreground shadow-xs backdrop-blur",
                "hover:bg-background hover:text-foreground",
                "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/60",
              )}
            >
              <span
                className={cn(
                  "h-2 w-2 rounded-full flex-shrink-0",
                  getStatusColor(activeConn?.status),
                )}
              />
              <span className="truncate font-medium">{activeConn?.label || "No connection"}</span>
              <ChevronDown className="ml-auto h-4 w-4 text-muted-foreground transition-colors group-hover:text-foreground" />
            </button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="start" className="w-64 p-2">
            {connections.length === 0 ? (
              <div className="px-3 py-4 text-center">
                <div className="text-xs text-muted-foreground mb-2">No connections yet</div>
                <DropdownMenuItem
                  onClick={onOpenSettings}
                  className="text-xs justify-center rounded-md bg-secondary hover:bg-secondary/80"
                >
                  <Plus className="h-3 w-3 mr-1.5" />
                  Add connection
                </DropdownMenuItem>
              </div>
            ) : (
              <>
                <div className="px-2 pb-1 text-[10px] font-medium text-muted-foreground uppercase tracking-wider">
                  Connections
                </div>
                {connections.map((conn) => (
                  <DropdownMenuItem
                    key={conn.id}
                    onClick={() => onConnectionChange(conn.id)}
                    className={cn(
                      "text-sm gap-2 cursor-pointer rounded-md px-2 py-1.5",
                      activeConnection === conn.id ? "bg-secondary text-foreground" : "text-muted-foreground hover:text-foreground",
                    )}
                  >
                    <span
                      className={cn(
                        "h-2 w-2 rounded-full flex-shrink-0 ring-2 ring-background shadow-sm",
                        getStatusColor(conn.status),
                      )}
                    />
                    <span className="truncate font-medium">{conn.label}</span>
                    {activeConnection === conn.id && (
                      <span className="ml-auto text-[10px] uppercase tracking-wide text-muted-foreground">
                        Active
                      </span>
                    )}
                  </DropdownMenuItem>
                ))}
                <DropdownMenuSeparator className="my-2" />
                <DropdownMenuItem
                  onClick={onOpenSettings}
                  className="text-sm text-muted-foreground rounded-md px-2 py-1.5 hover:text-foreground"
                >
                  <Plus className="h-4 w-4 mr-2" />
                  Manage connections...
                </DropdownMenuItem>
              </>
            )}
          </DropdownMenuContent>
        </DropdownMenu>

        <div className="relative">
          <Search className="absolute left-2.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            ref={searchInputRef}
            id="schema-sidebar-search"
            placeholder="Search tables & queries..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "ArrowDown") {
                e.preventDefault()
                // Focus first table or query item based on active tab
                const firstItem = activeTab === "tables"
                  ? document.querySelector('[data-table-index="0"]') as HTMLElement
                  : document.querySelector('[data-query-index="0"]') as HTMLElement
                firstItem?.focus()
              }
            }}
            className={cn(
              "h-9 pl-9 pr-9 bg-background/60 border-border shadow-xs backdrop-blur",
              "focus-visible:ring-ring/60",
            )}
          />
          {search && (
            <button
              onClick={() => setSearch("")}
              className="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
              aria-label="Clear search"
            >
              <X className="h-4 w-4" />
            </button>
          )}
        </div>
      </div>

      <Separator className="my-3 bg-border" />

      {/* Lists */}
      <div className="min-h-0 flex-1 overflow-auto">
        <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as "tables" | "queries")} className="gap-3 pr-1">
          <TabsList className="w-full flex bg-secondary/70 text-muted-foreground">
            <TabsTrigger value="tables" className="text-xs flex-1 min-w-0">
              <Table2 className="h-3.5 w-3.5 flex-shrink-0" />
              <span className="truncate">Tables</span>
              <Badge
                variant="secondary"
                className="ml-1 h-4 px-1.5 text-[10px] tabular-nums text-muted-foreground bg-background border-border flex-shrink-0"
              >
                {filteredTables.length}
              </Badge>
            </TabsTrigger>
            <TabsTrigger value="queries" className="text-xs flex-1 min-w-0">
              <Bookmark className="h-3.5 w-3.5 flex-shrink-0" />
              <span className="truncate">Saved</span>
              <Badge
                variant="secondary"
                className="ml-1 h-4 px-1.5 text-[10px] tabular-nums text-muted-foreground bg-background border-border flex-shrink-0"
              >
                {filteredQueries.length}
              </Badge>
            </TabsTrigger>
          </TabsList>

          <TabsContent value="tables" className="m-0 outline-none">
            {/* Tables header row with refresh (animated like DataGrid hide icon) */}
            <div className="group flex items-center gap-2 rounded-md px-2 py-1 text-xs font-medium text-muted-foreground hover:bg-secondary">
              <div className="flex items-center gap-2 min-w-0 flex-1">
                <span className="uppercase tracking-wide">Tables</span>
              </div>

              <div className="flex items-center gap-1">
                <Badge
                  variant="secondary"
                  className="h-5 px-1.5 text-[11px] tabular-nums text-muted-foreground bg-secondary border-border"
                >
                  {filteredTables.length}
                </Badge>

                {onRefreshSchema && (
                  <div
                    className={cn(
                      "transition-all duration-300 ease-in-out flex-shrink-0",
                      showActionsOnHover ? "w-0 overflow-hidden opacity-0 group-hover:w-5 group-hover:opacity-100" : "w-5 opacity-100",
                    )}
                  >
                    <button
                      onClick={() => onRefreshSchema()}
                      className="p-0.5 hover:bg-muted rounded text-muted-foreground hover:text-foreground transition-colors outline-none"
                      title="Refresh schema"
                    >
                      <RotateCcw className="h-3.5 w-3.5" />
                    </button>
                  </div>
                )}
              </div>
            </div>

            <div className="mt-1 space-y-1" ref={tableListRef}>
              {(() => {
                let flatIndex = -1
                const totalFlat = flatTableEntries.length
                return groupedTables.map(([schemaName, group]) => {
                  const collapsed = !isSearching && hasMultipleSchemas && collapsedSchemas.has(schemaName)
                  return (
                    <div key={schemaName}>
                      {hasMultipleSchemas && (
                        <button
                          onClick={() => toggleSchema(schemaName)}
                          className={cn(
                            "group/schema mt-1 flex h-7 w-full items-center gap-1.5 rounded-md px-2 text-left text-[11px] font-medium uppercase tracking-wide text-muted-foreground",
                            "hover:bg-secondary hover:text-foreground",
                            "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/60",
                          )}
                          aria-expanded={!collapsed}
                          title={`Schema: ${schemaName}`}
                        >
                          <ChevronRight
                            className={cn(
                              "h-3.5 w-3.5 text-muted-foreground transition-transform flex-shrink-0",
                              !collapsed && "rotate-90",
                            )}
                          />
                          <Database className="h-3 w-3 flex-shrink-0" />
                          <span className="truncate">{schemaName}</span>
                          <Badge
                            variant="secondary"
                            className="ml-auto h-4 px-1.5 text-[10px] tabular-nums text-muted-foreground bg-background border-border"
                          >
                            {group.length}
                          </Badge>
                        </button>
                      )}

                      {!collapsed && (
                        <div className={cn(hasMultipleSchemas && "ml-2 border-l border-border pl-2")}>
                          {group.map((table) => {
                            flatIndex += 1
                            const index = flatIndex
                            const expandKey = table.qualifiedName
                            const isExpanded = expandedTables.has(expandKey)
                            return (
                              <div key={table.qualifiedName}>
                                <div className="group/row flex items-center gap-1">
                                  <button
                                    data-table-index={index}
                                    onClick={() => toggleTable(expandKey)}
                                    onKeyDown={(e) => {
                                      if (e.key === "Enter") {
                                        e.preventDefault()
                                        onViewTable(table.qualifiedName)
                                        onFocusQuery?.()
                                      } else {
                                        handleListKeyDown(e, "data-table-index", index, totalFlat)
                                      }
                                    }}
                                    aria-expanded={isExpanded}
                                    className={cn(
                                      "flex h-8 min-w-0 flex-1 items-center gap-2 rounded-md px-2 text-left text-sm text-foreground",
                                      "hover:bg-secondary hover:text-foreground",
                                      "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/60",
                                    )}
                                  >
                                    <ChevronRight
                                      className={cn(
                                        "h-4 w-4 text-muted-foreground transition-transform flex-shrink-0",
                                        isExpanded && "rotate-90",
                                      )}
                                    />
                                    <span className="truncate">{table.name}</span>
                                    {table.kind === "view" && (
                                      <Badge className="h-4 rounded-sm px-1 text-[9px] bg-purple-100 dark:bg-purple-950 text-purple-800 dark:text-purple-400 border-purple-200 dark:border-purple-800 shrink-0">
                                        VIEW
                                      </Badge>
                                    )}
                                    {table.kind === "matview" && (
                                      <Badge className="h-4 rounded-sm px-1 text-[9px] bg-fuchsia-100 dark:bg-fuchsia-950 text-fuchsia-800 dark:text-fuchsia-400 border-fuchsia-200 dark:border-fuchsia-800 shrink-0">
                                        MV
                                      </Badge>
                                    )}
                                  </button>

                                  <div className="flex items-center">
                                    <div
                                      className={cn(
                                        "transition-all duration-300 ease-in-out flex-shrink-0",
                                        showActionsOnHover
                                          ? "w-0 overflow-hidden opacity-0 group-hover/row:w-8 group-hover/row:opacity-100"
                                          : "w-8 opacity-100",
                                      )}
                                    >
                                      <button
                                        onClick={(e) => {
                                          e.stopPropagation()
                                          onViewTable(table.qualifiedName)
                                        }}
                                        className="p-1 hover:bg-secondary rounded text-muted-foreground hover:text-foreground transition-colors outline-none"
                                        title="View top 100 rows"
                                      >
                                        <Eye className="h-4 w-4" />
                                      </button>
                                    </div>
                                    <div
                                      className={cn(
                                        "transition-all duration-300 ease-in-out flex-shrink-0",
                                        showActionsOnHover
                                          ? "w-0 overflow-hidden opacity-0 group-hover/row:w-8 group-hover/row:opacity-100"
                                          : "w-8 opacity-100",
                                      )}
                                    >
                                      <button
                                        onClick={(e) => {
                                          e.stopPropagation()
                                          openJoinBuilder(table.qualifiedName)
                                        }}
                                        className="p-1 hover:bg-secondary rounded text-muted-foreground hover:text-foreground transition-colors outline-none"
                                        title="Join with..."
                                      >
                                        <GitMerge className="h-4 w-4" />
                                      </button>
                                    </div>
                                  </div>
                                </div>

                                {isExpanded && (
                                  <div className="ml-4 mt-1 border-l border-border pl-3">
                                    {(table.indexes.length > 0 || table.triggers.length > 0) && (
                                      <div className="text-[9px] uppercase tracking-wider text-muted-foreground/70 px-2 pt-1 pb-0.5">
                                        Columns
                                      </div>
                                    )}
                                    <div className="space-y-0.5 pb-1">
                                      {table.columns.map((col) => (
                                        <div
                                          key={col.name}
                                          className={cn(
                                            "rounded-md px-2 py-1 text-xs text-foreground",
                                            "hover:bg-secondary/70",
                                          )}
                                        >
                                          <div className="flex items-center gap-2 min-w-0">
                                            <span
                                              className={cn(
                                                "truncate",
                                                col.isPk && "text-amber-700 dark:text-amber-400 font-medium",
                                                col.isFk && "text-blue-700 dark:text-blue-400 font-medium",
                                              )}
                                            >
                                              {col.name}
                                            </span>
                                            {col.isPk && (
                                              <Badge className="h-4 rounded-sm px-1 text-[10px] bg-amber-100 dark:bg-amber-950 text-amber-800 dark:text-amber-400 border-amber-200 dark:border-amber-800">
                                                PK
                                              </Badge>
                                            )}
                                            {col.isFk && (
                                              <Badge className="h-4 rounded-sm px-1 text-[10px] bg-blue-100 dark:bg-blue-950 text-blue-800 dark:text-blue-400 border-blue-200 dark:border-blue-800">
                                                FK
                                              </Badge>
                                            )}
                                            {col.isAuto && (
                                              <Badge className="h-4 rounded-sm px-1 text-[10px] bg-emerald-100 dark:bg-emerald-950 text-emerald-800 dark:text-emerald-400 border-emerald-200 dark:border-emerald-800">
                                                AUTO
                                              </Badge>
                                            )}
                                          </div>
                                          <div className="mt-0.5 truncate font-mono text-[10px] text-muted-foreground">
                                            {col.type}
                                          </div>
                                        </div>
                                      ))}
                                    </div>

                                    {table.indexes.length > 0 && (
                                      <>
                                        <div className="text-[9px] uppercase tracking-wider text-muted-foreground/70 px-2 pt-1 pb-0.5">
                                          Indexes
                                        </div>
                                        <div className="space-y-0.5 pb-1">
                                          {table.indexes.map((idx) => (
                                            <div
                                              key={idx.name}
                                              className="rounded-md px-2 py-1 text-xs text-foreground hover:bg-secondary/70"
                                              title={idx.definition}
                                            >
                                              <div className="flex items-center gap-2 min-w-0">
                                                <span className="truncate">{idx.name}</span>
                                                {idx.isUnique && (
                                                  <Badge className="h-4 rounded-sm px-1 text-[9px] bg-sky-100 dark:bg-sky-950 text-sky-800 dark:text-sky-400 border-sky-200 dark:border-sky-800 shrink-0">
                                                    UNIQUE
                                                  </Badge>
                                                )}
                                              </div>
                                              {idx.columns.length > 0 && (
                                                <div className="mt-0.5 truncate font-mono text-[10px] text-muted-foreground">
                                                  ({idx.columns.join(", ")})
                                                </div>
                                              )}
                                            </div>
                                          ))}
                                        </div>
                                      </>
                                    )}

                                    {table.triggers.length > 0 && (
                                      <>
                                        <div className="text-[9px] uppercase tracking-wider text-muted-foreground/70 px-2 pt-1 pb-0.5">
                                          Triggers
                                        </div>
                                        <div className="space-y-0.5 pb-1">
                                          {table.triggers.map((trg) => (
                                            <div
                                              key={trg.name}
                                              className="rounded-md px-2 py-1 text-xs text-foreground hover:bg-secondary/70"
                                              title={trg.definition}
                                            >
                                              <div className="flex items-center gap-2 min-w-0">
                                                <span className="truncate">{trg.name}</span>
                                              </div>
                                              <div className="mt-0.5 truncate font-mono text-[10px] text-muted-foreground">
                                                {trg.timing} {trg.events.join(" / ")}
                                              </div>
                                            </div>
                                          ))}
                                        </div>
                                      </>
                                    )}
                                  </div>
                                )}
                              </div>
                            )
                          })}
                        </div>
                      )}
                    </div>
                  )
                })
              })()}

              {filteredTables.length === 0 && search && (
                <div className="px-2 py-3 text-sm text-muted-foreground text-center">No tables found</div>
              )}

              {schema && schema.routines && schema.routines.length > 0 && (
                <RoutinesSection
                  routines={schema.routines}
                  search={searchLower}
                  onPick={(routine) => {
                    if (!onOpenSql) return
                    const qualified = `"${routine.schema}"."${routine.name}"`
                    const sql =
                      routine.kind === "procedure"
                        ? `CALL ${qualified}();`
                        : `SELECT * FROM ${qualified}();`
                    onOpenSql(sql, `${routine.schema}.${routine.name}`)
                    onFocusQuery?.()
                  }}
                />
              )}
            </div>
          </TabsContent>

          <TabsContent value="queries" className="m-0 outline-none">
            {/* Queries header row with sync controls */}
            <div className="group flex items-center gap-2 rounded-md px-2 py-1 text-xs font-medium text-muted-foreground hover:bg-secondary">
              <div className="flex items-center gap-2 min-w-0 flex-1">
                <span className="uppercase tracking-wide">Saved queries</span>
              </div>

              <div className="flex items-center gap-1">
                <Badge
                  variant="secondary"
                  className="h-5 px-1.5 text-[11px] tabular-nums text-muted-foreground bg-secondary border-border"
                >
                  {filteredQueries.length}
                </Badge>

                {onOpenSyncSettings && (
                  <div
                    className={cn(
                      "transition-all duration-300 ease-in-out flex-shrink-0",
                      showActionsOnHover ? "w-0 overflow-hidden opacity-0 group-hover:w-5 group-hover:opacity-100" : "w-5 opacity-100",
                    )}
                  >
                    <button
                      onClick={() => onOpenSyncSettings()}
                      className="p-0.5 hover:bg-muted rounded text-muted-foreground hover:text-foreground transition-colors outline-none"
                      title="Sync settings"
                    >
                      <KeyRound className="h-3.5 w-3.5" />
                    </button>
                  </div>
                )}

                {onSyncNamedQueries && (
                  <div
                    className={cn(
                      "transition-all duration-300 ease-in-out flex-shrink-0",
                      showActionsOnHover ? "w-0 overflow-hidden opacity-0 group-hover:w-5 group-hover:opacity-100" : "w-5 opacity-100",
                    )}
                  >
                    <button
                      onClick={() => onSyncNamedQueries()}
                      className="p-0.5 hover:bg-muted rounded text-muted-foreground hover:text-foreground transition-colors outline-none"
                      title="Sync saved queries"
                    >
                      <RotateCcw className="h-3.5 w-3.5" />
                    </button>
                  </div>
                )}
              </div>
            </div>

            <div className="space-y-0.5" ref={queryListRef}>
              {filteredQueries.map((nq, index) => (
                <div key={nq.id} className="group/item flex items-center">
                  <button
                    data-query-index={index}
                    onClick={() => onOpenNamedQuery(nq.id)}
                    onKeyDown={(e) => {
                      if (e.key === "Enter") {
                        e.preventDefault()
                        onOpenNamedQuery(nq.id)
                        onFocusQuery?.()
                      } else {
                        handleListKeyDown(e, "data-query-index", index, filteredQueries.length)
                      }
                    }}
                    className={cn(
                      "flex h-8 flex-1 items-center gap-2 rounded-md px-2 text-left text-sm text-foreground",
                      "hover:bg-secondary hover:text-foreground",
                      "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/60",
                    )}
                  >
                    <Bookmark className="h-4 w-4 text-muted-foreground group-hover/item:text-foreground" />
                    <span className="truncate">{nq.name}</span>
                  </button>
                  {onDeleteNamedQuery && (
                    <div
                      className={cn(
                        "transition-all duration-300 ease-in-out flex-shrink-0",
                        showActionsOnHover
                          ? "w-0 overflow-hidden opacity-0 group-hover/item:w-8 group-hover/item:opacity-100"
                          : "w-8 opacity-100",
                      )}
                    >
                      <button
                        onClick={(e) => {
                          e.stopPropagation()
                          onDeleteNamedQuery(nq.id)
                        }}
                        className="p-1 hover:bg-destructive/10 rounded text-muted-foreground hover:text-destructive transition-colors outline-none"
                        title="Delete saved query"
                      >
                        <X className="h-4 w-4" />
                      </button>
                    </div>
                  )}
                </div>
              ))}

              {filteredQueries.length === 0 && search && (
                <div className="px-2 py-3 text-sm text-muted-foreground text-center">No queries found</div>
              )}
              {filteredQueries.length === 0 && !search && (
                <div className="px-2 py-3 text-sm text-muted-foreground text-center">No saved queries yet</div>
              )}
            </div>
          </TabsContent>
        </Tabs>
      </div>

      <JoinBuilderDialog
        open={joinDialogOpen}
        onOpenChange={setJoinDialogOpen}
        baseTable={joinBaseTable}
        tables={tables}
        onCreateJoin={onJoinTables}
      />
    </div>
  )
}

// ---- Routines (functions / procedures / aggregates) -----------------------

type RoutineRow = NonNullable<SchemaGraph["routines"]>[number]

function RoutinesSection({
  routines,
  search,
  onPick,
}: {
  routines: RoutineRow[]
  search: string
  onPick: (routine: RoutineRow) => void
}) {
  const [collapsed, setCollapsed] = useState(true)

  const filtered = useMemo(() => {
    if (!search) return routines
    const s = search.toLowerCase()
    return routines.filter(
      (r) => r.name.toLowerCase().includes(s) || r.schema.toLowerCase().includes(s),
    )
  }, [routines, search])

  // While searching, force-expand so matches are visible.
  const isOpen = search ? true : !collapsed

  if (filtered.length === 0) return null

  return (
    <div className="mt-3">
      <button
        onClick={() => setCollapsed(!collapsed)}
        className={cn(
          "flex h-6 w-full items-center gap-2 rounded-md px-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground",
          "hover:bg-secondary hover:text-foreground",
        )}
        aria-expanded={isOpen}
      >
        <ChevronRight
          className={cn(
            "h-3.5 w-3.5 text-muted-foreground transition-transform flex-shrink-0",
            isOpen && "rotate-90",
          )}
        />
        <span className="truncate">Routines</span>
        <Badge
          variant="secondary"
          className="ml-auto h-4 px-1.5 text-[10px] tabular-nums text-muted-foreground bg-background border-border"
        >
          {filtered.length}
        </Badge>
      </button>

      {isOpen && (
        <div className="ml-2 border-l border-border pl-2 mt-1 space-y-0.5">
          {filtered.map((r) => (
            <button
              key={`${r.schema}.${r.name}.${r.argsSignature}`}
              onClick={() => onPick(r)}
              className={cn(
                "block w-full text-left rounded-md px-2 py-1 text-xs",
                "hover:bg-secondary/70 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/60",
              )}
              title={`${r.schema}.${r.name}(${r.argsSignature})${r.returnType ? ` → ${r.returnType}` : ""}`}
            >
              <div className="flex items-center gap-2 min-w-0">
                <span className="truncate">{r.name}</span>
                {r.kind !== "function" && (
                  <Badge className="h-4 rounded-sm px-1 text-[9px] bg-indigo-100 dark:bg-indigo-950 text-indigo-800 dark:text-indigo-400 border-indigo-200 dark:border-indigo-800 shrink-0 uppercase">
                    {r.kind === "procedure" ? "PROC" : r.kind === "aggregate" ? "AGG" : "WIN"}
                  </Badge>
                )}
              </div>
              <div className="mt-0.5 truncate font-mono text-[10px] text-muted-foreground">
                {r.schema}
                {r.argsSignature ? ` (${r.argsSignature})` : "()"}
                {r.returnType ? ` → ${r.returnType}` : ""}
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  )
}
