import type { ColumnInfo } from "@/lib/schema-introspection"

const AUTO_DEFAULT_PATTERNS = [
  /\bnextval\(/i, // serial/identity sequences
  /\bgen_random_uuid\(\)/i,
  /\buuid_generate_v/i,
  /\buuid_generate\(\)/i,
  /\bnow\(\)/i,
  /\bcurrent_timestamp\b/i,
  /\bclock_timestamp\(\)/i,
  /\bstatement_timestamp\(\)/i,
  /\btransaction_timestamp\(\)/i,
  /\blocaltimestamp\b/i,
  /\blocaltime\b/i,
]

export function isAutoGeneratedColumn(column: ColumnInfo): boolean {
  if (column.isIdentity) return true
  if (column.isGenerated) return true
  if (column.generationExpression) return true

  const defaultValue = column.defaultValue?.trim()
  if (defaultValue) {
    for (const pat of AUTO_DEFAULT_PATTERNS) {
      if (pat.test(defaultValue)) return true
    }
  }

  return false
}

export function guessParamType(dataType: string): "string" | "number" | "boolean" {
  const t = dataType.toLowerCase()
  if (t.includes("bool")) return "boolean"
  if (
    t.includes("int") ||
    t.includes("numeric") ||
    t.includes("decimal") ||
    t.includes("double") ||
    t.includes("real") ||
    t.includes("money") ||
    t.includes("float")
  ) {
    return "number"
  }
  return "string"
}
